### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by tabam1** [Step7750/node-csgo-cdn#14]
Try: 
Sealed Graffiti | HellRaisers | Atlanta 2017 
and 
Sticker | HellRaisers | Atlanta 2017
This same result :) 
https://steamcdn-a.akamaihd.net/apps/730/icons/econ/stickers/atlanta2017/hlr_large.389cb3f3b08a3a66f2a2d3921d0292f585347975.png

**Comment by Step7750** [comment]
Fixed in v1.1.2
