### ISSUE TITLE
Tinted Graffiti

### ISSUE THREAD

**Issue by tabam1** [Step7750/node-csgo-cdn#20]
Does not work for graffiti with color
e.g: Sealed Graffiti | Popdog (Blood Red)
return (https://steamcdn-a.akamaihd.net/apps/730/icons/econ/stickers/default/popdog_large.e248a907ba21ac78e30df6653eebd8f0090e3a83.png)

**Comment by Step7750** [comment]
This is stated on the overview page of what the library can retrieve. It may be possible to retrieve a specific tint image as well in the VPKs, but I'd have to go through that again.
