### ISSUE TITLE
No such file

### ISSUE THREAD

**Issue by tabam1** [Step7750/node-csgo-cdn#28]
Look screen
![Screen](https://user-images.githubusercontent.com/47059021/83267264-3d294c00-a1c4-11ea-92b8-093fbe36a1e6.png)

**Comment by denkomanceski** [comment]
It seems like the manifest file contains another file which "endsWith('pak01_dir')" so it is pulling the wrong file. Also when the file is pulled, it is not saved as pak01_dir but its original name which is platform_pak01_dir. I will open a PR that fixes this
