### ISSUE TITLE
Missing Items

### ISSUE THREAD

**Issue by jayjo29** [Step7750/node-csgo-cdn#3]
Hello :-)

Unfortunately, around 3000 weapons/items can't be found, one of them is "MP7 | Army Recon (Minimal Wear)".
Please tell if a vpk Package is missing, because you told in Readme that Package 57, 83 and 84 are important ones, but i only see  package 57, 63, 83 in my data folder.

Thanks for your help :-)

**Comment by Step7750** [comment]
Looks like Valve decided to change the case of some paint kit descriptions (`#PaintKit_sp_spray_army_Tag` vs `#Paintkit_sp_spray_army_Tag`) in items_game and csgo_english. I'll add a fix shortly.
