### ISSUE TITLE
Cannot retrieve cases

### ISSUE THREAD

**Issue by NexusNovaz** [Step7750/node-csgo-cdn#33]
```

const SteamUser = require('steam-user');
const csgoCDN = require('csgo-cdn');

const user = new SteamUser();
user.logOn("XXXXXXXXXXXXX", "XXXXXXXXXXXXXXXXX")
const cdn = new csgoCDN(user, {logLevel: 'debug'});
cdn.on('ready', () => {
   console.log(cdn.getItemNameURL("Fracture Case"));
});
```

After writing that it returns; 
`[csgo-image-cdn] error: Failed to retrieve resource/flash/econ/weapon_cases/crate_community_26.png in VPK, do you have the package category enabled in options?`

**Comment by Step7750** [comment]
Cloned v1.2.0 with a test account and successfully retrieved the URL for "Fracture Case" (https://steamcdn-a.akamaihd.net/apps/730/icons/econ/weapon_cases/crate_community_26.b25098af5a4285004052786e261be43dec5b89cf.png)

Please re-open if you still have issues.
